// ============================================
// DINNER PICKER - 200 DINNER OPTIONS
// Random dinner suggestions for movie night
// ============================================

const DINNERS = [
    // Italian Cuisine
    { name: "Spaghetti Carbonara", category: "Italian" },
    { name: "Lasagna", category: "Italian" },
    { name: "Fettuccine Alfredo", category: "Italian" },
    { name: "Penne Arrabbiata", category: "Italian" },
    { name: "Risotto Mushroom", category: "Italian" },
    { name: "Osso Buco", category: "Italian" },
    { name: "Tiramisu", category: "Italian Dessert" },
    { name: "Eggplant Parmesan", category: "Italian" },
    { name: "Ravioli with Pesto", category: "Italian" },
    { name: "Minestrone Soup", category: "Italian" },
    
    // Mexican Cuisine
    { name: "Chicken Enchiladas", category: "Mexican" },
    { name: "Beef Tacos", category: "Mexican" },
    { name: "Chile Relleno", category: "Mexican" },
    { name: "Carne Asada", category: "Mexican" },
    { name: "Chiles en Nogada", category: "Mexican" },
    { name: "Pollo con Mole", category: "Mexican" },
    { name: "Street Tacos", category: "Mexican" },
    { name: "Quesadillas with Cheese", category: "Mexican" },
    { name: "Pozole Rojo", category: "Mexican" },
    { name: "Chiles Stuffed with Queso", category: "Mexican" },
    
    // American Cuisine
    { name: "Grilled Hamburgers", category: "American" },
    { name: "BBQ Ribs", category: "American" },
    { name: "Fried Chicken", category: "American" },
    { name: "Meatloaf with Mashed Potatoes", category: "American" },
    { name: "Mac and Cheese", category: "American" },
    { name: "Pulled Pork Sandwich", category: "American" },
    { name: "Pot Roast", category: "American" },
    { name: "Grilled Steak", category: "American" },
    { name: "Chicken and Dumplings", category: "American" },
    { name: "New York Cheesecake", category: "American Dessert" },
    
    // Asian Cuisine
    { name: "Kung Pao Chicken", category: "Asian" },
    { name: "Pad Thai", category: "Asian" },
    { name: "Beef Teriyaki", category: "Asian" },
    { name: "Fried Rice", category: "Asian" },
    { name: "Sushi Rolls", category: "Asian" },
    { name: "Ramen Noodles", category: "Asian" },
    { name: "Sesame Chicken", category: "Asian" },
    { name: "Pho", category: "Asian" },
    { name: "General Tso's Chicken", category: "Asian" },
    { name: "Lo Mein Noodles", category: "Asian" },
    
    // Mediterranean/Greek
    { name: "Moussaka", category: "Mediterranean" },
    { name: "Souvlaki", category: "Mediterranean" },
    { name: "Greek Salad with Feta", category: "Mediterranean" },
    { name: "Spanakopita", category: "Mediterranean" },
    { name: "Falafel Wraps", category: "Mediterranean" },
    { name: "Tzatziki with Pita", category: "Mediterranean" },
    { name: "Hummus Platter", category: "Mediterranean" },
    { name: "Tabbouleh Salad", category: "Mediterranean" },
    { name: "Grilled Octopus", category: "Mediterranean" },
    { name: "Baklava", category: "Mediterranean Dessert" },
    
    // Indian Cuisine
    { name: "Butter Chicken", category: "Indian" },
    { name: "Chicken Tikka Masala", category: "Indian" },
    { name: "Saag Paneer", category: "Indian" },
    { name: "Biryani", category: "Indian" },
    { name: "Tandoori Chicken", category: "Indian" },
    { name: "Chana Masala", category: "Indian" },
    { name: "Aloo Gobi", category: "Indian" },
    { name: "Samosas", category: "Indian" },
    { name: "Naan Bread", category: "Indian" },
    { name: "Gulab Jamun", category: "Indian Dessert" },
    
    // French Cuisine
    { name: "Coq au Vin", category: "French" },
    { name: "Beef Bourguignon", category: "French" },
    { name: "Sole Meunière", category: "French" },
    { name: "Duck Confit", category: "French" },
    { name: "Crème Brûlée", category: "French Dessert" },
    { name: "Cassoulet", category: "French" },
    { name: "Escargot", category: "French" },
    { name: "Filet Mignon", category: "French" },
    { name: "Ratatouille", category: "French" },
    { name: "French Onion Soup", category: "French" },
    
    // Seafood
    { name: "Grilled Salmon", category: "Seafood" },
    { name: "Shrimp Scampi", category: "Seafood" },
    { name: "Fish and Chips", category: "Seafood" },
    { name: "Lobster Tails", category: "Seafood" },
    { name: "Crab Cakes", category: "Seafood" },
    { name: "Mussels in White Wine", category: "Seafood" },
    { name: "Clam Chowder", category: "Seafood" },
    { name: "Tuna Steak", category: "Seafood" },
    { name: "Paella", category: "Seafood" },
    { name: "Baked Cod", category: "Seafood" },
    
    // Vegetarian/Vegan
    { name: "Vegetable Stir Fry", category: "Vegetarian" },
    { name: "Bean Chili", category: "Vegetarian" },
    { name: "Stuffed Bell Peppers", category: "Vegetarian" },
    { name: "Veggie Burger", category: "Vegetarian" },
    { name: "Tofu Pad Thai", category: "Vegetarian" },
    { name: "Quinoa Bowl", category: "Vegetarian" },
    { name: "Caprese Salad", category: "Vegetarian" },
    { name: "Veggie Pizza", category: "Vegetarian" },
    { name: "Lentil Soup", category: "Vegetarian" },
    { name: "Buddha Bowl", category: "Vegetarian" },
    
    // Comfort Food
    { name: "Grilled Cheese Sandwich", category: "Comfort Food" },
    { name: "Tomato Soup", category: "Comfort Food" },
    { name: "Baked Beans", category: "Comfort Food" },
    { name: "Cornbread", category: "Comfort Food" },
    { name: "Biscuits and Gravy", category: "Comfort Food" },
    { name: "Turkey Meatballs", category: "Comfort Food" },
    { name: "Chicken Noodle Soup", category: "Comfort Food" },
    { name: "French Toast", category: "Comfort Food" },
    { name: "Pancakes", category: "Comfort Food" },
    { name: "Fried Egg Sandwich", category: "Comfort Food" },
    
    // BBQ/Grilled
    { name: "BBQ Chicken", category: "BBQ" },
    { name: "Grilled Vegetables", category: "BBQ" },
    { name: "Hot Dogs", category: "BBQ" },
    { name: "Beef Brisket", category: "BBQ" },
    { name: "Grilled Corn", category: "BBQ" },
    { name: "BBQ Pulled Chicken", category: "BBQ" },
    { name: "Tri-Tip Steak", category: "BBQ" },
    { name: "Grilled Lamb Chops", category: "BBQ" },
    { name: "Chicken Skewers", category: "BBQ" },
    { name: "Smoked Turkey", category: "BBQ" },
    
    // World Cuisine
    { name: "Shawarma", category: "Middle Eastern" },
    { name: "Falafel", category: "Middle Eastern" },
    { name: "Kimchi and Rice", category: "Korean" },
    { name: "Korean BBQ", category: "Korean" },
    { name: "Bibimbap", category: "Korean" },
    { name: "Tacos al Pastor", category: "Mexican" },
    { name: "Empanadas", category: "Latin American" },
    { name: "Ceviche", category: "Latin American" },
    { name: "Goulash", category: "European" },
    { name: "Schnitzel", category: "European" },
    
    // Breakfast for Dinner
    { name: "Scrambled Eggs with Toast", category: "Breakfast" },
    { name: "Breakfast Burritos", category: "Breakfast" },
    { name: "Waffle and Bacon", category: "Breakfast" },
    { name: "Omelette", category: "Breakfast" },
    { name: "Hash Browns with Eggs", category: "Breakfast" },
    { name: "Breakfast Pizza", category: "Breakfast" },
    { name: "Pancakes and Sausage", category: "Breakfast" },
    { name: "Eggs Benedict", category: "Breakfast" },
    { name: "Breakfast Sandwich", category: "Breakfast" },
    { name: "Shakshuka", category: "Breakfast" },
    
    // Pizza & Pasta Variations
    { name: "Margherita Pizza", category: "Italian" },
    { name: "Pepperoni Pizza", category: "Italian" },
    { name: "Supreme Pizza", category: "Italian" },
    { name: "White Pizza", category: "Italian" },
    { name: "Tortellini Alfredo", category: "Italian" },
    { name: "Gnocchi", category: "Italian" },
    { name: "Baked Ziti", category: "Italian" },
    { name: "Penne Primavera", category: "Italian" },
    { name: "Macaroni and Cheese", category: "Italian-American" },
    { name: "Spaghetti with Meatballs", category: "Italian-American" },
    
    // Light/Healthy Options
    { name: "Grilled Chicken Breast", category: "Healthy" },
    { name: "Steamed Broccoli", category: "Healthy" },
    { name: "Turkey Meatloaf", category: "Healthy" },
    { name: "Salmon with Lemon", category: "Healthy" },
    { name: "Veggie Spring Rolls", category: "Healthy" },
    { name: "Chickpea Salad", category: "Healthy" },
    { name: "Kale Caesar Salad", category: "Healthy" },
    { name: "Turkey Burger", category: "Healthy" },
    { name: "Grilled Fish Tacos", category: "Healthy" },
    { name: "Lean Ground Beef", category: "Healthy" },
    
    // Slow Cooker/Easy Meals
    { name: "Slow Cooker Chili", category: "Easy" },
    { name: "Pulled Pork", category: "Easy" },
    { name: "Slow Cooker Stew", category: "Easy" },
    { name: "Crockpot Chicken", category: "Easy" },
    { name: "Beef Stew", category: "Easy" },
    { name: "Slow Cooker Tacos", category: "Easy" },
    { name: "Crockpot Roast", category: "Easy" },
    { name: "Slow Cooker Curry", category: "Easy" },
    { name: "Crockpot Soup", category: "Easy" },
    { name: "Slow Cooker Ribs", category: "Easy" },
    
    // Spicy Options
    { name: "Spicy Chicken Wings", category: "Spicy" },
    { name: "Spicy Sriracha Noodles", category: "Spicy" },
    { name: "Hot and Spicy Curry", category: "Spicy" },
    { name: "Jalapeño Chicken", category: "Spicy" },
    { name: "Spicy Korean Stew", category: "Spicy" },
    { name: "Ghost Pepper Chili", category: "Spicy" },
    { name: "Spicy Shrimp Pasta", category: "Spicy" },
    { name: "Thai Red Curry", category: "Spicy" },
    { name: "Habanero Tacos", category: "Spicy" },
    { name: "Spicy Beef Satay", category: "Spicy" }
];