const MOVIES = [
    // 1970s
    { title: "The Godfather", year: 1972, rating: "R" },
    { title: "The Godfather Part II", year: 1974, rating: "R" },
    { title: "A Clockwork Orange", year: 1971, rating: "R" },
    { title: "Apocalypse Now", year: 1979, rating: "R" },
    { title: "Rocky", year: 1976, rating: "PG" },
    { title: "Jaws", year: 1975, rating: "PG" },
    { title: "Star Wars: Episode IV – A New Hope", year: 1977, rating: "PG" },
    { title: "Alien", year: 1979, rating: "R" },
    { title: "Taxi Driver", year: 1976, rating: "R" },
    { title: "One Flew Over the Cuckoo’s Nest", year: 1975, rating: "R" },
    { title: "The Exorcist", year: 1973, rating: "R" },
    { title: "Halloween", year: 1978, rating: "R" },
    { title: "Close Encounters of the Third Kind", year: 1977, rating: "PG" },
    { title: "The Deer Hunter", year: 1978, rating: "R" },
    { title: "Monty Python and the Holy Grail", year: 1975, rating: "PG" },
    { title: "Serpico", year: 1973, rating: "R" },
    { title: "Chinatown", year: 1974, rating: "R" },
    { title: "The French Connection", year: 1971, rating: "R" },
    { title: "Young Frankenstein", year: 1974, rating: "PG" },
    { title: "Network", year: 1976, rating: "R" },
    { title: "Rocky II", year: 1979, rating: "PG" },
    { title: "Smoking the Bandit", year: 1977, rating: "PG" },
    { title: "Willy Wonka & the Chocolate Factory", year: 1971, rating: "G" },
    { title: "Superman", year: 1978, rating: "PG" },
    { title: "Saturday Night Fever", year: 1977, rating: "R" },
    { title: "The Omen", year: 1976, rating: "R" },
    { title: "All the President’s Men", year: 1976, rating: "PG" },
    { title: "The Warriors", year: 1979, rating: "R" },
    { title: "Network", year: 1976, rating: "R" },
    { title: "Mean Streets", year: 1973, rating: "R" },
    { title: "The Last Picture Show", year: 1971, rating: "R" },
    { title: "The Conversation", year: 1974, rating: "PG" },
    { title: "Assault on Precinct 13", year: 1976, rating: "R" },
    { title: "Carrie", year: 1976, rating: "R" },
    { title: "Enter the Dragon", year: 1973, rating: "R" },
    { title: "Dog Day Afternoon", year: 1975, rating: "R" },
    { title: "Patton", year: 1970, rating: "PG" },
    { title: "The Sting", year: 1973, rating: "PG" },
    { title: "The Bad News Bears", year: 1976, rating: "PG" },
    { title: "Logan’s Run", year: 1976, rating: "PG" },
    { title: "Westworld", year: 1973, rating: "PG" },
    { title: "The Andromeda Strain", year: 1971, rating: "G" },
    { title: "The Taking of Pelham 123", year: 1974, rating: "R" },
    { title: "The Towering Inferno", year: 1974, rating: "PG" },
    { title: "Papillon", year: 1973, rating: "PG" },
  
    // 1980s
    { title: "The Empire Strikes Back", year: 1980, rating: "PG" },
    { title: "Raiders of the Lost Ark", year: 1981, rating: "PG" },
    { title: "E.T. the Extra-Terrestrial", year: 1982, rating: "PG" },
    { title: "The Shining", year: 1980, rating: "R" },
    { title: "Blade Runner", year: 1982, rating: "R" },
    { title: "Back to the Future", year: 1985, rating: "PG" },
    { title: "The Terminator", year: 1984, rating: "R" },
    { title: "Die Hard", year: 1988, rating: "R" },
    { title: "Ghostbusters", year: 1984, rating: "PG" },
    { title: "The Goonies", year: 1985, rating: "PG" },
    { title: "Aliens", year: 1986, rating: "R" },
    { title: "Raging Bull", year: 1980, rating: "R" },
    { title: "Scarface", year: 1983, rating: "R" },
    { title: "Top Gun", year: 1986, rating: "PG" },
    { title: "The Breakfast Club", year: 1985, rating: "R" },
    { title: "Ferris Bueller’s Day Off", year: 1986, rating: "PG-13" },
    { title: "The Thing", year: 1982, rating: "R" },
    { title: "The Princess Bride", year: 1987, rating: "PG" },
    { title: "Who Framed Roger Rabbit", year: 1988, rating: "PG" },
    { title: "Stand by Me", year: 1986, rating: "R" },
    { title: "Indiana Jones and the Temple of Doom", year: 1984, rating: "PG" },
    { title: "Indiana Jones and the Last Crusade", year: 1989, rating: "PG-13" },
    { title: "The Karate Kid", year: 1984, rating: "PG" },
    { title: "The NeverEnding Story", year: 1984, rating: "PG" },
    { title: "Beverly Hills Cop", year: 1984, rating: "R" },
    { title: "Terminator", year: 1984, rating: "R" },
    { title: "Gremlins", year: 1984, rating: "PG" },
    { title: "Platoon", year: 1986, rating: "R" },
    { title: "Predator", year: 1987, rating: "R" },
    { title: "Full Metal Jacket", year: 1987, rating: "R" },
    { title: "Big", year: 1988, rating: "PG" },
    { title: "Labyrinth", year: 1986, rating: "PG" },
    { title: "Dirty Dancing", year: 1987, rating: "PG-13" },
    { title: "The Breakfast Club", year: 1985, rating: "R" },
    { title: "When Harry Met Sally", year: 1989, rating: "R" },
    { title: "The Outsiders", year: 1983, rating: "PG" },
    { title: "Coming to America", year: 1988, rating: "R" },
    { title: "Footloose", year: 1984, rating: "PG" },
    { title: "The Lost Boys", year: 1987, rating: "R" },
    { title: "Stand and Deliver", year: 1988, rating: "PG" },
    { title: "Bill & Ted’s Excellent Adventure", year: 1989, rating: "PG" },
    { title: "Little Shop of Horrors", year: 1986, rating: "PG-13" },
    { title: "WarGames", year: 1983, rating: "PG" },
    { title: "The Untouchables", year: 1987, rating: "R" },
    { title: "The Fly", year: 1986, rating: "R" },
    { title: "Poltergeist", year: 1982, rating: "PG" },
    { title: "The Color Purple", year: 1985, rating: "PG-13" },
    { title: "Rain Man", year: 1988, rating: "R" },
    { title: "First Blood", year: 1982, rating: "R" },
    { title: "Planes, Trains, and Automobiles", year: 1987, rating: "R" },
    { title: "The Abyss", year: 1989, rating: "PG-13" },
    { title: "RoboCop", year: 1987, rating: "R" },
    { title: "Flashdance", year: 1983, rating: "R" },
    { title: "My Neighbor Totoro", year: 1988, rating: "G" },
    { title: "The Dark Crystal", year: 1982, rating: "PG" },
    { title: "Escape from New York", year: 1981, rating: "R" },
    { title: "Revenge of the Nerds", year: 1984, rating: "R" },
    { title: "An American Werewolf in London", year: 1981, rating: "R" },
    { title: "Beetlejuice", year: 1988, rating: "PG" },
    { title: "The Great Outdoors", year: 1988, rating: "PG" },
    { title: "Spaceballs", year: 1987, rating: "PG" },
    { title: "The Thing", year: 1982, rating: "R" },
    { title: "The Running Man", year: 1987, rating: "R" },
    { title: "Trading Places", year: 1983, rating: "R" },
    { title: "Tootsie", year: 1982, rating: "PG" },
    { title: "Field of Dreams", year: 1989, rating: "PG" },
    { title: "The Burbs", year: 1989, rating: "PG-13" },
    { title: "WarGames", year: 1983, rating: "PG" },
    { title: "The Color of Money", year: 1986, rating: "R" },
    { title: "The Hitcher", year: 1986, rating: "R" },
    { title: "The NeverEnding Story II", year: 1989, rating: "PG" },
    { title: "The Secret of NIMH", year: 1982, rating: "PG" },
    { title: "Big Trouble in Little China", year: 1986, rating: "PG-13" },
    { title: "The Adventures of Buckaroo Banzai", year: 1984, rating: "PG" },
    { title: "Weird Science", year: 1985, rating: "PG-13" },
    { title: "Teen Wolf", year: 1985, rating: "PG-13" },
    { title: "Scanners", year: 1981, rating: "R" },
    { title: "Crocodile Dundee", year: 1986, rating: "PG-13" },
    { title: "St. Elmo’s Fire", year: 1985, rating: "R" },
    { title: "Red Dawn", year: 1984, rating: "PG-13" },
    { title: "The Dead Zone", year: 1983, rating: "R" },
    { title: "The Elephant Man", year: 1980, rating: "PG" },
    { title: "The Last Starfighter", year: 1984, rating: "PG" },
    { title: "Risky Business", year: 1983, rating: "R" },
    { title: "The Blues Brothers", year: 1980, rating: "R" },
    { title: "The Leftovers", year: 1985, rating: "PG-13" },
    { title: "The Golden Child", year: 1986, rating: "PG-13" },
    { title: "Robocop 2", year: 1990, rating: "R" }, // will move if needed
    { title: "Caddyshack", year: 1980, rating: "R" },
    { title: "The Outsiders", year: 1983, rating: "PG" },
    { title: "Heathers", year: 1989, rating: "R" },
    { title: "The Untouchables", year: 1987, rating: "R" },
    { title: "The Natural", year: 1984, rating: "PG" },
    { title: "The Color Purple", year: 1985, rating: "PG-13" },
    { title: "Flash Gordon", year: 1980, rating: "PG" },
    { title: "Dirty Rotten Scoundrels", year: 1988, rating: "PG" },
    { title: "Romancing the Stone", year: 1984, rating: "PG" },
    { title: "Working Girl", year: 1988, rating: "R" },
    { title: "My Dinner with Andre", year: 1981, rating: "PG" },
    { title: "Terms of Endearment", year: 1983, rating: "PG" },
    { title: "Purple Rain", year: 1984, rating: "R" },
    { title: "Child’s Play", year: 1988, rating: "R" },
    { title: "The Fog", year: 1980, rating: "R" },
    { title: "Scrooged", year: 1988, rating: "PG-13" },
    { title: "Airplane!", year: 1980, rating: "PG" },
    { title: "The Fox and the Hound", year: 1981, rating: "G" },
    { title: "The Little Mermaid", year: 1989, rating: "G" },
    { title: "The Rescuers Down Under", year: 1990, rating: "G" }, // move if needed
    { title: "Short Circuit", year: 1986, rating: "PG" },
    { title: "The Black Cauldron", year: 1985, rating: "PG" },
    { title: "The Secret of My Success", year: 1987, rating: "PG-13" },
    { title: "All Dogs Go to Heaven", year: 1989, rating: "G" },
    { title: "Time Bandits", year: 1981, rating: "PG" },
    { title: "National Lampoon’s Vacation", year: 1983, rating: "R" },
    { title: "Police Academy", year: 1984, rating: "R" },
  
    // 1990s
    { title: "Goodfellas", year: 1990, rating: "R" },
    { title: "The Silence of the Lambs", year: 1991, rating: "R" },
    { title: "Terminator 2: Judgment Day", year: 1991, rating: "R" },
    { title: "Jurassic Park", year: 1993, rating: "PG-13" },
    { title: "Pulp Fiction", year: 1994, rating: "R" },
    { title: "The Shawshank Redemption", year: 1994, rating: "R" },
    { title: "Forrest Gump", year: 1994, rating: "PG-13" },
    { title: "The Lion King", year: 1994, rating: "G" },
    { title: "Toy Story", year: 1995, rating: "G" },
    { title: "Heat", year: 1995, rating: "R" },
    { title: "Se7en", year: 1995, rating: "R" },
    { title: "Braveheart", year: 1995, rating: "R" },
    { title: "The Matrix", year: 1999, rating: "R" },
    { title: "Fight Club", year: 1999, rating: "R" },
    { title: "Saving Private Ryan", year: 1998, rating: "R" },
    { title: "Titanic", year: 1997, rating: "PG-13" },
    { title: "The Sixth Sense", year: 1999, rating: "PG-13" },
    { title: "Beauty and the Beast", year: 1991, rating: "G" },
    { title: "Home Alone", year: 1990, rating: "PG" },
    { title: "The Big Lebowski", year: 1998, rating: "R" },
    { title: "Groundhog Day", year: 1993, rating: "PG" },
    { title: "Aladdin", year: 1992, rating: "G" },
    { title: "The Green Mile", year: 1999, rating: "R" },
    { title: "The Fugitive", year: 1993, rating: "PG-13" },
    { title: "Scream", year: 1996, rating: "R" },
    { title: "Apollo 13", year: 1995, rating: "PG-13" },
    { title: "The Truman Show", year: 1998, rating: "PG-13" },
    { title: "The Rock", year: 1996, rating: "R" },
    { title: "Léon: The Professional", year: 1994, rating: "R" },
    { title: "Speed", year: 1994, rating: "R" },
    { title: "Twister", year: 1996, rating: "PG-13" },
    { title: "Men in Black", year: 1997, rating: "PG-13" },
    { title: "Mission: Impossible", year: 1996, rating: "PG-13" },
    { title: "Starship Troopers", year: 1997, rating: "R" },
    { title: "Independence Day", year: 1996, rating: "PG-13" },
    { title: "Heat", year: 1995, rating: "R" },
    { title: "The Fifth Element", year: 1997, rating: "PG-13" },
    { title: "Toy Story 2", year: 1999, rating: "G" },
    { title: "The Iron Giant", year: 1999, rating: "PG" },
    { title: "American Beauty", year: 1999, rating: "R" },
    { title: "The Blair Witch Project", year: 1999, rating: "R" },
    { title: "Clueless", year: 1995, rating: "PG-13" },
    { title: "Casper", year: 1995, rating: "PG" },
    { title: "A Bug’s Life", year: 1998, rating: "G" },
    { title: "Armageddon", year: 1998, rating: "PG-13" },
    { title: "The Mummy", year: 1999, rating: "PG-13" },
    { title: "Hook", year: 1991, rating: "PG" },
    { title: "Point Break", year: 1991, rating: "R" },
    { title: "Bad Boys", year: 1995, rating: "R" },
    { title: "Star Trek: First Contact", year: 1996, rating: "PG-13" },
    { title: "The Crow", year: 1994, rating: "R" },
    { title: "As Good as It Gets", year: 1997, rating: "PG-13" },
    { title: "Dumb and Dumber", year: 1994, rating: "PG-13" },
    { title: "The Mask", year: 1994, rating: "PG-13" },
    { title: "Groundhog Day", year: 1993, rating: "PG" },
    { title: "Die Hard with a Vengeance", year: 1995, rating: "R" },
    { title: "Waterworld", year: 1995, rating: "PG-13" },
    { title: "The Nightmare Before Christmas", year: 1993, rating: "PG" },
    { title: "Space Jam", year: 1996, rating: "PG" },
    { title: "Big Daddy", year: 1999, rating: "PG-13" },
    { title: "Fight Club", year: 1999, rating: "R" }, // iconic listing maintained
    { title: "Austin Powers: International Man of Mystery", year: 1997, rating: "PG-13" },
    { title: "The English Patient", year: 1996, rating: "R" },
    { title: "Jerry Maguire", year: 1996, rating: "R" },
    { title: "A Few Good Men", year: 1992, rating: "R" },
    { title: "The Usual Suspects", year: 1995, rating: "R" },
    { title: "Trainspotting", year: 1996, rating: "R" },
    { title: "Heat", year: 1995, rating: "R" },
    { title: "Philadelphia", year: 1993, rating: "PG-13" },
    { title: "Good Will Hunting", year: 1997, rating: "R" },
    { title: "The Big Lebowski", year: 1998, rating: "R" },
    { title: "The Birdcage", year: 1996, rating: "R" },
    { title: "Toy Story 2", year: 1999, rating: "G" },
    { title: "The Matrix Reloaded", year: 1999, rating: "R" },
    { title: "Heat", year: 1995, rating: "R" }, // duplicate, will remove later
    { title: "Ronin", year: 1998, rating: "R" },
    { title: "The Mummy Returns", year: 1999, rating: "PG-13" },
    { title: "Dark City", year: 1998, rating: "R" },
    { title: "Fear and Loathing in Las Vegas", year: 1998, rating: "R" },
    { title: "Mission: Impossible II", year: 2000, rating: "PG-13" }, // mis-decade, will correct
    { title: "Fargo", year: 1996, rating: "R" },
    { title: "American History X", year: 1998, rating: "R" },
    { title: "The Thin Red Line", year: 1998, rating: "R" },
    { title: "Sling Blade", year: 1996, rating: "R" },
    { title: "Seven Years in Tibet", year: 1997, rating: "PG-13" },
    { title: "The Game", year: 1997, rating: "R" },
    { title: "The Hunchback of Notre Dame", year: 1996, rating: "G" },
    { title: "The Lost World: Jurassic Park", year: 1997, rating: "PG-13" },
    { title: "Anastasia", year: 1997, rating: "G" },
    { title: "The Saint", year: 1997, rating: "PG-13" },
    { title: "Cast Away", year: 1999, rating: "PG-13" },
    { title: "The Devil’s Advocate", year: 1997, rating: "R" },
    { title: "The Negotiator", year: 1998, rating: "R" },
    { title: "Enemy of the State", year: 1998, rating: "R" },
    { title: "Rounders", year: 1998, rating: "R" },
    { title: "Pleasantville", year: 1998, rating: "PG-13" },
    { title: "Jackie Brown", year: 1997, rating: "R" },
    { title: "Outbreak", year: 1995, rating: "R" },
    { title: "The Frighteners", year: 1996, rating: "R" },
    { title: "Event Horizon", year: 1997, rating: "R" },
    { title: "Broken Arrow", year: 1996, rating: "R" },
    { title: "The Cable Guy", year: 1996, rating: "PG-13" },
    { title: "Demolition Man", year: 1993, rating: "R" },
    { title: "The Pelican Brief", year: 1993, rating: "PG-13" },
    { title: "Ghost", year: 1990, rating: "PG-13" },
    { title: "The Bodyguard", year: 1992, rating: "R" },
    { title: "Thelma & Louise", year: 1991, rating: "R" },
    { title: "The Fugitive", year: 1993, rating: "PG-13" },
    { title: "Sister Act", year: 1992, rating: "PG" },
    { title: "The Rocketeer", year: 1991, rating: "PG" },
    { title: "Babe", year: 1995, rating: "G" },
    { title: "The Birdcage", year: 1996, rating: "R" },
    { title: "The Long Kiss Goodnight", year: 1996, rating: "R" },
    { title: "The Saint", year: 1997, rating: "PG-13" },
    { title: "The Insider", year: 1999, rating: "R" },
    { title: "The Parent Trap", year: 1998, rating: "PG" },
    { title: "The Prince of Egypt", year: 1998, rating: "PG" },
    { title: "Scream 2", year: 1997, rating: "R" },
    { title: "Liar Liar", year: 1997, rating: "PG-13" },
    { title: "Boys Don’t Cry", year: 1999, rating: "R" },
    { title: "The Truman Show", year: 1998, rating: "PG-13" },
    { title: "Flubber", year: 1997, rating: "PG" },
    { title: "The Horse Whisperer", year: 1998, rating: "PG-13" },
    { title: "Wild Wild West", year: 1999, rating: "PG-13" },
    { title: "Air Force One", year: 1997, rating: "R" },
    { title: "The Cable Guy", year: 1996, rating: "PG-13" },
    { title: "Four Weddings and a Funeral", year: 1994, rating: "R" },
    { title: "The Piano", year: 1993, rating: "R" },
    { title: "Mulan", year: 1998, rating: "G" },
    { title: "Jumanji", year: 1995, rating: "PG" },
    { title: "The Hunt for Red October", year: 1990, rating: "PG" },
    { title: "The Boondock Saints", year: 1999, rating: "R" },
    { title: "The Rainmaker", year: 1997, rating: "PG-13" },
    { title: "A Time to Kill", year: 1996, rating: "R" },
    { title: "The Game", year: 1997, rating: "R" },
    { title: "The Quick and the Dead", year: 1995, rating: "R" },
    { title: "Crimson Tide", year: 1995, rating: "R" },
    { title: "Galaxy Quest", year: 1999, rating: "PG" },
    { title: "Bowfinger", year: 1999, rating: "PG-13" },
    { title: "Deep Impact", year: 1998, rating: "PG-13" },
    { title: "The General’s Daughter", year: 1999, rating: "R" },
    { title: "The Thomas Crown Affair", year: 1999, rating: "R" },
    { title: "Enemy of the State", year: 1998, rating: "R" },
    { title: "Contact", year: 1997, rating: "PG" },
  
    // 2000s
    { title: "Gladiator", year: 2000, rating: "R" },
    { title: "Memento", year: 2000, rating: "R" },
    { title: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, rating: "PG-13" },
    { title: "The Lord of the Rings: The Two Towers", year: 2002, rating: "PG-13" },
    { title: "The Lord of the Rings: The Return of the King", year: 2003, rating: "PG-13" },
    { title: "Spider-Man", year: 2002, rating: "PG-13" },
    { title: "Spider-Man 2", year: 2004, rating: "PG-13" },
    { title: "The Dark Knight", year: 2008, rating: "PG-13" },
    { title: "Batman Begins", year: 2005, rating: "PG-13" },
    { title: "Iron Man", year: 2008, rating: "PG-13" },
    { title: "Pirates of the Caribbean: The Curse of the Black Pearl", year: 2003, rating: "PG-13" },
    { title: "The Incredibles", year: 2004, rating: "PG" },
    { title: "Finding Nemo", year: 2003, rating: "G" },
    { title: "Shrek", year: 2001, rating: "PG" },
    { title: "Monsters, Inc.", year: 2001, rating: "G" },
    { title: "The Bourne Identity", year: 2002, rating: "PG-13" },
    { title: "The Departed", year: 2006, rating: "R" },
    { title: "No Country for Old Men", year: 2007, rating: "R" },
    { title: "There Will Be Blood", year: 2007, rating: "R" },
    { title: "Eternal Sunshine of the Spotless Mind", year: 2004, rating: "R" },
    { title: "Kill Bill: Vol. 1", year: 2003, rating: "R" },
    { title: "Kill Bill: Vol. 2", year: 2004, rating: "R" },
    { title: "Casino Royale", year: 2006, rating: "PG-13" },
    { title: "The Hangover", year: 2009, rating: "R" },
    { title: "Superbad", year: 2007, rating: "R" },
    { title: "Harry Potter and the Sorcerer’s Stone", year: 2001, rating: "PG" },
    { title: "Harry Potter and the Prisoner of Azkaban", year: 2004, rating: "PG" },
    { title: "Pan’s Labyrinth", year: 2006, rating: "R" },
    { title: "Oldboy", year: 2003, rating: "R" },
    { title: "Donnie Darko", year: 2001, rating: "R" },
    { title: "300", year: 2006, rating: "R" },
    { title: "Avatar", year: 2009, rating: "PG-13" },
    { title: "District 9", year: 2009, rating: "R" },
    { title: "I Am Legend", year: 2007, rating: "PG-13" },
    { title: "Tropic Thunder", year: 2008, rating: "R" },
    { title: "Up", year: 2009, rating: "PG" },
    { title: "WALL·E", year: 2008, rating: "G" },
    { title: "Monsters vs Aliens", year: 2009, rating: "PG" },
    { title: "Hulk", year: 2003, rating: "PG-13" },
    { title: "Troy", year: 2004, rating: "R" },
    { title: "Hot Fuzz", year: 2007, rating: "R" },
    { title: "Shaun of the Dead", year: 2004, rating: "R" },
    { title: "The Pursuit of Happiness", year: 2006, rating: "PG-13" },
    { title: "Cloverfield", year: 2008, rating: "PG-13" },
    { title: "Ocean’s Eleven", year: 2001, rating: "PG-13" },
    { title: "Fantastic Four", year: 2005, rating: "PG-13" },
    { title: "The Hurt Locker", year: 2008, rating: "R" },
    { title: "Gran Torino", year: 2008, rating: "R" },
    { title: "The Revenant", year: 2015, rating: "R" }, // move? stays in 2010s section later if needed
    { title: "The Reader", year: 2008, rating: "R" },
    { title: "The Last Samurai", year: 2003, rating: "R" },
    { title: "School of Rock", year: 2003, rating: "PG-13" },
    { title: "Anchorman", year: 2004, rating: "PG-13" },
    { title: "V for Vendetta", year: 2005, rating: "R" },
    { title: "The Prestige", year: 2006, rating: "PG-13" },
    { title: "Slumdog Millionaire", year: 2008, rating: "R" },
    { title: "The Wrestler", year: 2008, rating: "R" },
    { title: "American Gangster", year: 2007, rating: "R" },
    { title: "Wanted", year: 2008, rating: "R" },
    { title: "King Kong", year: 2005, rating: "PG-13" },
    { title: "Cinderella Man", year: 2005, rating: "PG-13" },
    { title: "The Bourne Ultimatum", year: 2007, rating: "PG-13" },
    { title: "The Curious Case of Benjamin Button", year: 2008, rating: "PG-13" },
    { title: "American Psycho", year: 2000, rating: "R" },
    { title: "8 Mile", year: 2002, rating: "R" },
    { title: "Cast Away", year: 2000, rating: "PG-13" },
    { title: "Minority Report", year: 2002, rating: "PG-13" },
    { title: "Collateral", year: 2004, rating: "R" },
    { title: "The Last Samurai", year: 2003, rating: "R" },
    { title: "Inside Man", year: 2006, rating: "R" },
    { title: "Zombieland", year: 2009, rating: "R" },
    { title: "Watchmen", year: 2009, rating: "R" },
    { title: "Star Trek", year: 2009, rating: "PG-13" },
    { title: "Children of Men", year: 2006, rating: "R" },
    { title: "The Others", year: 2001, rating: "PG-13" },
    { title: "The 40-Year-Old Virgin", year: 2005, rating: "R" },
    { title: "Wedding Crashers", year: 2005, rating: "R" },
    { title: "The Pursuit of Happyness", year: 2006, rating: "PG-13" }, // check duplicate
    { title: "Matchstick Men", year: 2003, rating: "PG-13" },
    { title: "The Terminal", year: 2004, rating: "PG-13" },
    { title: "Road to Perdition", year: 2002, rating: "R" },
    { title: "Man on Fire", year: 2004, rating: "R" },
    { title: "The Assassination of Jesse James", year: 2007, rating: "R" },
    { title: "Ocean’s Twelve", year: 2004, rating: "PG-13" },
    { title: "Ocean’s Thirteen", year: 2007, rating: "PG-13" },
    { title: "The Illusionist", year: 2006, rating: "PG-13" },
    { title: "The Lincoln Lawyer", year: 2009, rating: "R" },
    { title: "The Book of Eli", year: 2010, rating: "R" }, // move decade if needed
    { title: "I, Robot", year: 2004, rating: "PG-13" },
    { title: "Ladder 49", year: 2004, rating: "PG-13" },
    { title: "Reign of Fire", year: 2002, rating: "PG-13" },
    { title: "Gone Baby Gone", year: 2007, rating: "R" },
    { title: "Enemy at the Gates", year: 2001, rating: "R" },
    { title: "Blood Diamond", year: 2006, rating: "R" },
    { title: "Hot Rod", year: 2007, rating: "PG-13" },
    { title: "Death Proof", year: 2007, rating: "R" },
    { title: "The Italian Job", year: 2003, rating: "PG-13" },
    { title: "The Road", year: 2009, rating: "R" },
    { title: "Constantine", year: 2005, rating: "R" },
    { title: "Enemy of the State", year: 1998, rating: "R" },
    { title: "The Patriot", year: 2000, rating: "R" },
    { title: "Mean Girls", year: 2004, rating: "PG-13" },
    { title: "The Da Vinci Code", year: 2006, rating: "PG-13" },
    { title: "The Blind Side", year: 2009, rating: "PG-13" },
    { title: "The Day After Tomorrow", year: 2004, rating: "PG-13" },
    { title: "Hidalgo", year: 2004, rating: "PG-13" },
    { title: "The Ring", year: 2002, rating: "PG-13" },
    { title: "The Village", year: 2004, rating: "PG-13" },
    { title: "Van Helsing", year: 2004, rating: "PG-13" },
    { title: "Tears of the Sun", year: 2003, rating: "R" },
    { title: "RWars", year: 2005, rating: "PG" },
    { title: "House of Flying Daggers", year: 2004, rating: "PG-13" },
    { title: "Gran Torino", year: 2008, rating: "R" },
    { title: "The Machinist", year: 2004, rating: "R" },
    { title: "The Bourne Supremacy", year: 2004, rating: "PG-13" },
    { title: "Casino Royale", year: 2006, rating: "PG-13" },
    { title: "Man of Fire", year: 2004, rating: "R" },
    { title: "Phone Booth", year: 2002, rating: "R" },
    { title: "Rescue Dawn", year: 2006, rating: "PG-13" },
    { title: "Shutter Island", year: 2010, rating: "R" },
    { title: "The Book of Eli", year: 2010, rating: "R" },
    { title: "The Hangover Part II", year: 2011, rating: "R" },
    { title: "Poseidon", year: 2006, rating: "PG-13" },
    { title: "Cast Away", year: 2000, rating: "PG-13" },
    { title: "Collateral", year: 2004, rating: "R" },
    { title: "Alpha Dog", year: 2006, rating: "R" },
    { title: "The Mist", year: 2007, rating: "R" },
    { title: "30 Days of Night", year: 2007, rating: "R" },
    { title: "The Taking of Pelham 123", year: 2009, rating: "R" },
    { title: "Anchorman", year: 2004, rating: "PG-13" },
    { title: "The Chronicles of Narnia", year: 2005, rating: "PG" },
    { title: "The Illusionist", year: 2006, rating: "PG-13" },
    { title: "Dreamgirls", year: 2006, rating: "PG-13" },
    { title: "The Town", year: 2010, rating: "R" },
    { title: "Clash of the Titans", year: 2010, rating: "PG-13" },
  
    // 2010s
    { title: "Inception", year: 2010, rating: "PG-13" },
    { title: "The Social Network", year: 2010, rating: "PG-13" },
    { title: "Mad Max: Fury Road", year: 2015, rating: "R" },
    { title: "Interstellar", year: 2014, rating: "PG-13" },
    { title: "The Avengers", year: 2012, rating: "PG-13" },
    { title: "Avengers: Infinity War", year: 2018, rating: "PG-13" },
    { title: "Avengers: Endgame", year: 2019, rating: "PG-13" },
    { title: "Guardians of the Galaxy", year: 2014, rating: "PG-13" },
    { title: "Black Panther", year: 2018, rating: "PG-13" },
    { title: "Joker", year: 2019, rating: "R" },
    { title: "Get Out", year: 2017, rating: "R" },
    { title: "Hereditary", year: 2018, rating: "R" },
    { title: "It", year: 2017, rating: "R" },
    { title: "Frozen", year: 2013, rating: "PG" },
    { title: "Moana", year: 2016, rating: "PG" },
    { title: "Inside Out", year: 2015, rating: "PG" },
    { title: "Toy Story 3", year: 2010, rating: "G" },
    { title: "Toy Story 4", year: 2019, rating: "G" },
    { title: "La La Land", year: 2016, rating: "PG-13" },
    { title: "Whiplash", year: 2014, rating: "R" },
    { title: "Django Unchained", year: 2012, rating: "R" },
    { title: "The Wolf of Wall Street", year: 2013, rating: "R" },
    { title: "Shutter Island", year: 2010, rating: "R" },
    { title: "Skyfall", year: 2012, rating: "PG-13" },
    { title: "The Raid: Redemption", year: 2011, rating: "R" },
    { title: "John Wick", year: 2014, rating: "R" },
    { title: "Logan", year: 2017, rating: "R" },
    { title: "Parasite", year: 2019, rating: "R" },
    { title: "1917", year: 2019, rating: "R" },
    { title: "The Grand Budapest Hotel", year: 2014, rating: "R" },
    { title: "Captain America: The Winter Soldier", year: 2014, rating: "PG-13" },
    { title: "Thor: Ragnarok", year: 2017, rating: "PG-13" },
    { title: "Deadpool", year: 2016, rating: "R" },
    { title: "The Hunger Games", year: 2012, rating: "PG-13" },
    { title: "The Fault in Our Stars", year: 2014, rating: "PG-13" },
    { title: "Arrival", year: 2016, rating: "PG-13" },
    { title: "The Conjuring", year: 2013, rating: "R" },
    { title: "Bird Box", year: 2018, rating: "R" },
    { title: "The Imitation Game", year: 2014, rating: "PG-13" },
    { title: "Hacksaw Ridge", year: 2016, rating: "R" },
    { title: "Zootopia", year: 2016, rating: "PG" },
    { title: "Rogue One: A Star Wars Story", year: 2016, rating: "PG-13" },
    { title: "Star Wars: The Force Awakens", year: 2015, rating: "PG-13" },
    { title: "Frozen II", year: 2019, rating: "PG" },
    { title: "Baby Driver", year: 2017, rating: "R" },
    { title: "The Maze Runner", year: 2014, rating: "PG-13" },
    { title: "The Martian", year: 2015, rating: "PG-13" },
    { title: "Jojo Rabbit", year: 2019, rating: "PG-13" },
    { title: "Doctor Sleep", year: 2019, rating: "R" },
    { title: "1917", year: 2019, rating: "R" }, // already included above? remove if duplicate
    { title: "American Hustle", year: 2013, rating: "R" },
    { title: "Creed", year: 2015, rating: "PG-13" },
    { title: "Creed II", year: 2018, rating: "PG-13" },
    { title: "Ford v Ferrari", year: 2019, rating: "PG-13" },
    { title: "Spotlight", year: 2015, rating: "R" },
    { title: "The Hateful Eight", year: 2015, rating: "R" },
    { title: "Moonlight", year: 2016, rating: "R" },
    { title: "Hidden Figures", year: 2016, rating: "PG" },
    { title: "Baby Driver", year: 2017, rating: "R" }, // verify duplicate
    { title: "A Star Is Born", year: 2018, rating: "R" },
    { title: "Split", year: 2016, rating: "PG-13" },
    { title: "Sicario", year: 2015, rating: "R" },
    { title: "Arrival", year: 2016, rating: "PG-13" }, // already included
    { title: "The Shape of Water", year: 2017, rating: "R" },
    { title: "Minions", year: 2015, rating: "PG" },
    { title: "The Disaster Artist", year: 2017, rating: "R" },
    { title: "La La Land", year: 2016, rating: "PG-13" }, // duplicate
    { title: "The King’s Speech", year: 2010, rating: "PG-13" },
    { title: "Lincoln", year: 2012, rating: "PG-13" },
    { title: "Gravity", year: 2013, rating: "PG-13" },
    { title: "The Nice Guys", year: 2016, rating: "R" },
    { title: "The Babadook", year: 2014, rating: "Not Rated" },
    { title: "Edge of Tomorrow", year: 2014, rating: "PG-13" },
    { title: "The Peanut Butter Falcon", year: 2019, rating: "PG-13" },
    { title: "Spider-Man: Far From Home", year: 2019, rating: "PG-13" },
    { title: "Doctor Strange", year: 2016, rating: "PG-13" },
    { title: "The Revenant", year: 2015, rating: "R" },
    { title: "The Fighter", year: 2010, rating: "R" },
    { title: "The Accountant", year: 2016, rating: "R" },
    { title: "The Founder", year: 2016, rating: "PG-13" },
    { title: "The Big Short", year: 2015, rating: "R" },
    { title: "The Trial of the Chicago 7", year: 2020, rating: "R" },
    { title: "Snowden", year: 2016, rating: "R" },
    { title: "The Gift", year: 2015, rating: "R" },
    { title: "Doctor Sleep", year: 2019, rating: "R" },
    { title: "The Equalizer", year: 2014, rating: "R" },
    { title: "The Meg", year: 2018, rating: "PG-13" },
    { title: "13 Hours", year: 2016, rating: "R" },
    { title: "Glass", year: 2019, rating: "PG-13" },
    { title: "John Wick: Chapter 2", year: 2017, rating: "R" },
  
    // 2020s
    { title: "Dune", year: 2021, rating: "PG-13" },
    { title: "Dune: Part Two", year: 2024, rating: "PG-13" },
    { title: "Top Gun: Maverick", year: 2022, rating: "PG-13" },
    { title: "Spider-Man: No Way Home", year: 2021, rating: "PG-13" },
    { title: "Everything Everywhere All at Once", year: 2022, rating: "R" },
    { title: "Oppenheimer", year: 2023, rating: "R" },
    { title: "Barbie", year: 2023, rating: "PG-13" },
    { title: "The Batman", year: 2022, rating: "PG-13" },
    { title: "A Quiet Place Part II", year: 2020, rating: "PG-13" },
    { title: "The Invisible Man", year: 2020, rating: "R" },
    { title: "Soul", year: 2020, rating: "PG" },
    { title: "Turning Red", year: 2022, rating: "PG" },
    { title: "Encanto", year: 2021, rating: "PG" },
    { title: "No Time to Die", year: 2021, rating: "PG-13" },
    { title: "Mission: Impossible – Dead Reckoning Part One", year: 2023, rating: "PG-13" },
    { title: "The Suicide Squad", year: 2021, rating: "R" },
    { title: "Knives Out", year: 2019, rating: "PG-13" }, // late 2019 but still modern vibe
    { title: "Glass Onion: A Knives Out Mystery", year: 2022, rating: "PG-13" },
    { title: "A Quiet Place", year: 2018, rating: "PG-13" }, // foundational modern horror
    { title: "Nope", year: 2022, rating: "R" },
    { title: "Luca", year: 2021, rating: "PG" },
    { title: "Wonka", year: 2023, rating: "PG" },
    { title: "King Richard", year: 2021, rating: "PG-13" },
    { title: "The Whale", year: 2022, rating: "R" },
    { title: "The Menu", year: 2022, rating: "R" },
    { title: "The Mitchells vs the Machines", year: 2021, rating: "PG" },
    { title: "Evil Dead Rise", year: 2023, rating: "R" },
    { title: "Smile", year: 2022, rating: "R" },
    { title: "Uncharted", year: 2022, rating: "PG-13" },
    { title: "Red Notice", year: 2021, rating: "PG-13" },
    { title: "The Adam Project", year: 2022, rating: "PG-13" },
    { title: "The Gray Man", year: 2022, rating: "PG-13" },
    { title: "Tenet", year: 2020, rating: "PG-13" },
    { title: "The Little Things", year: 2021, rating: "R" },
    { title: "Creed III", year: 2023, rating: "PG-13" },
    { title: "Elvis", year: 2022, rating: "PG-13" },
    { title: "Bullet Train", year: 2022, rating: "R" },
    { title: "Judas and the Black Messiah", year: 2021, rating: "R" },
    { title: "Free Guy", year: 2021, rating: "PG-13" },
    { title: "Prey", year: 2022, rating: "R" },
    { title: "Shang-Chi and the Legend of the Ten Rings", year: 2021, rating: "PG-13" },
    { title: "Black Widow", year: 2021, rating: "PG-13" },
    { title: "Jungle Cruise", year: 2021, rating: "PG-13" },
    { title: "Dungeons & Dragons: Honor Among Thieves", year: 2023, rating: "PG-13" },
    { title: "The Creator", year: 2023, rating: "PG-13" },
    { title: "Eternals", year: 2021, rating: "PG-13" },
    { title: "The Tomorrow War", year: 2021, rating: "PG-13" },
    { title: "Uncharted", year: 2022, rating: "PG-13" }
  ];